### ISSUE TITLE
Caddy reverse proxy and sshwifty: HTTP Error (403): To use Websocket interface, a valid Auth Key must be provided

### ISSUE THREAD

**Issue by GFNiko** [nirui/sshwifty#130]
Nevermind, suddenly it works. Please delete

**Comment by nirui** [comment]
Sorry for the bother.

Judging by the randomness of occurrence, this specific problem might be caused by datetime difference between the server and the client. Making sure the both party has the correct datetime setup should prevent this. You can sync their times via a NTP server.

Another possibility is a plain-old-mistyped login password, but if true then the problem will never magically go away (it'll always give you this warning when a wrong password is used).

Hope it helped :)
