### ISSUE TITLE
How to perform keyword search on terminal output results?

### ISSUE THREAD

**Issue by haowanxing** [nirui/sshwifty#169]
Currently, in the open terminal interface, I'm unable to utilize the browser's built-in search functionality to search for keywords directly. Is there a feasible text search solution provided by the software, excluding the use of Linux commands like grep or similar to perform searches directly on the terminal?

I'm looking for an alternative method that would allow me to easily find specific information within the output displayed in the terminal, preferably without resorting to command-line tools like grep or similar. Any suggestions or features that could assist with this would be greatly appreciated.

**Comment by nirui** [comment]
Sorry, currently Sshwifty don't support searching through console output, which is not a reliable source to search from anyway, since older output might be flushed out by the newer ones as they generate.

As you've mentioned, the best way to search/filtering the console output is still with command such as `grep` (and maybe `tee` or redirect it beforehand).

**Comment by haowanxing** [comment]
tks
