### ISSUE TITLE
join cult

### ISSUE THREAD

**Issue by writeblankspace** [nirui/sshwifty#172]
How does one join the cult to access the Executive Golden Premium Plus+ Platinum Ultimate AD-free version?

**Comment by nirui** [comment]
Sorry, in order to join the cult, you must have already joined the cult. If you're not already a member, then the cult will never let you join.

If you're not a member, don't be sad. If the Multiverse Theory is true, then statistically speaking there is a non-zero chance that you are a member in other universes. So, just simply travel to one of those universe and get the Executive Golden Premium Plus+ Platinum Ultimate AD-free version there.

Hope this answers your question. I'll close this issue for now, feel free to re-open it if needed :)
