### ISSUE TITLE
Add a Autoconnect Feature

### ISSUE THREAD

**Issue by wnoisephx** [nirui/sshwifty#39]
Would it be possible to ask for an auto connect feature, such that if you connect on the web side of things it will automatically open  a ssh or telnet preset?

There are 2 ways I can see this working.   
1) Either a config option in the preset like: "Autoconnect": True 
and/or
2) If you only have only 1 preset and you have "OnlyAllowPresetRemotes": True then automatically connect to that preset.

Thank you

**Comment by nirui** [comment]
Sorry, but that's not what Presets was meant to be used. Preset was designed to allow the operator to auto-fill some of the inputs on the Preset Connector Wizard for the user. Later, the user is expected to reconnect to the remote through the "Connected Before" record without go through the Preset Connector Wizard again.

And because it's just an auto-fill, we must give user a chance to confirm the settings before they connect to the remote, thus, the wizard cannot be skipped.

So I'm afraid you must do the connect manually. Sorry.

Also, be alerted, the data defined in Presets are downloaded to the client where user can see it in clear text. So it's really not recommended to use it in such way.

**Comment by wnoisephx** [comment]
My use case is a bit different, as I just need a web/ssl to telnet interface for some old software that doesn't support anything else, and I only need/want the one telnet connection.  The clear text is not an issue, as the preset just has the remote telnet host.

Anyway thanks for the reply, and I will see if I can give a go on my own.

**Comment by nirui** [comment]
If the target host was a Telnet, then you might give "Launch Links" a look, for example: https://sshwifty.herokuapp.com/#+Telnet:horizons.jpl.nasa.gov:6775%7Cutf-8

This will give you the Autoconnect feature, sort of. It works because the Launch Link for Telnet contains all the information needed to establish a Telnet connection (Remote host address plus the charset). It does not work for SSH through, because you have to input some fields manually as the link will not not contain those info.

You can generate the link through the record listed on the "Connected Before" list. If you hover your mouse pointer on the record, you'll see "Copy Link", click it, then the link will be copied for you to paste.
