### ISSUE TITLE
true for resolve

### ISSUE THREAD

**Issue by AlexandroGonSan** [nirui/sshwifty#46]
![image](https://user-images.githubusercontent.com/38570195/114205828-b804dc80-9928-11eb-8700-3506fc0ab296.png)
![image](https://user-images.githubusercontent.com/38570195/114205858-be935400-9928-11eb-9307-88d14877d106.png)

**Comment by nirui** [comment]
Hello.

The error means Sshwifty cannot connect to the specified host.

There is no SSH service running locally on the server where the Sshwifty demo is deployed, thus connect to the server (via address `localhost`) will result a failure.

If your intention was to connect to your own machine from the demo service, maybe try use your public IP address instead of `localhost`. Of course, for this to work, your computer must have an IP address for the Internet.

You can also deploy Sshwifty on your `localhost` so it can actually connect to the SSH service on your machine.
