### ISSUE TITLE
Add support for multiple timezones

### ISSUE THREAD

**Issue by sambhavsaggi** [nirui/sshwifty#50]
If I have a deployment that I expect people from the Pacific coast to access a server on the eastern coast, the readme states that it'll fail.

Is there any way to fix this? I'm honestly getting sick of using Guacamole.

**Comment by nirui** [comment]
If by timezone you mean the one from "[The time difference is beyond operational limit]" error, well, it already been handled and should not cause problem when the user and the server are in different timezone (Otherwise, it's a bug).

[The time difference is beyond operational limit]: https://github.com/nirui/sshwifty#why-the-software-says-the-time-difference-is-beyond-operational-limit

There should not be any other time related timezone issue. If you are experiencing the very error, try resync the time on both the client and the server with a NTP service so they all have correct datetime in their respective timezone. Or, in a more technical tone, the "The time difference is beyond operational limit" error could only appear if the timezone-normalized time difference between the user and the server is greater than 15 approximately seconds ([= 30 seconds / 2](https://github.com/nirui/sshwifty/blob/1d05a9189b9c6b0dbdd59a90aac7c88a03c99ed3/ui/app.js#L40)).

**Comment by sambhavsaggi** [comment]
Alright. I just wanted to be sure that I wouldn't run into any issues once I deployed this. Maybe the README could be a little more clear? I'll see if I can make a PR.

Thanks!

**Comment by nirui** [comment]
I have given it [another take](https://github.com/nirui/sshwifty/blob/8f3a8d22909ed4b1625fde9521184eb989b9fa31/README.md#why-the-software-says-the-time-difference-is-beyond-operational-limit) (currently in dev branch). Hope this one is better than the last one :)
