### ISSUE TITLE
Re-enable arm64 in docker

### ISSUE THREAD

**Issue by tiagoqpinto** [nirui/sshwifty#53]
Is it possible to re-enable arm64 in docker?
Thanks!

**Comment by nirui** [comment]
Sorry, I don't think so, at least for now. 

Long story short, we are using `qemu` to "cross build" our Docker images, but `qemu` often fail on arm64 builds. Which is why it's been removed in the first place.

I'm still figuring out how to get around the problem. In the mean time, you can: 

* Manually create one with the [pre-built binaries], which is the fastest way. Or,
* Build one yourself with the `Dockerfile` provided by the project (that is, clone the project and then run `docker build --name sshwifty .` on your own arm64 machine)

[pre-built binaries]: https://github.com/nirui/sshwifty/releases/latest

**Comment by tiagoqpinto** [comment]
Thank you for the answer.
Keep with the really good work!
