### ISSUE TITLE
Getting a "Connection failed" when trying to login with SSH

### ISSUE THREAD

**Issue by ecmeyva** [nirui/sshwifty#80]
I am getting this error while trying to SSH local machine.

"Connection failed
ssh: unexpected packet in response to channel open: <nil>"

**Comment by nirui** [comment]
Hi,

I'm pretty sure it's a user-end issue. Can you share a bit more about your configuration and running environment?

Thanks! :D

**Comment by ecmeyva** [comment]
Oh, sorry about that. This is my first time on Github creating an issue.

I am running Ubuntu 18.04 and I also installed a media server solution called Cloudbox. Also sshwifty is running on docker.

Is there a way to see sshwifty log files. If so I am willing to post them too.

Thanks for your quick reply!

**Comment by nirui** [comment]
Can you try connect the SSH host again but with it's public IP address instead of `localhost` or `127.0.0.1`?

By default programs running in a Docker container uses an isolated virtual network, the address `localhost` and `127.0.0.1` inside a container points to the container itself rather than the host machine.

**Comment by ecmeyva** [comment]
Actually I was trying to connect with the public IP adress. After your message I tried to connect with 127.0.0.1 and got `dial tcp 127.0.0.1:22: connect: connection refused`.

**Comment by nirui** [comment]
Oh, that's odd. We might need to do more test in order to figure out that's going on, please following these steps:

1. On the machine which hosts the container, run command `docker inspect -f "{{ .State.Pid }}" <the ID of the container running Sshwifty>`, which will return the PID of Sshwifty's main process.
2. Then run `nsenter -t <the PID obtained in previous step> -n ssh <Target SSH user>@<Target SSH host>`, this will execute `ssh` command under the same network context as your Sshwifty instance.

Can the `ssh` command in step 2 connect to your SSH server?

**Comment by ecmeyva** [comment]
Yes, I am able to connect my server with this commands.

The weird thing is, I am able to connect with sshwifty once after I do a reboot. But if I end that connection and I try to connect with sshwifty I get the error on the original post.Anyway, I tried your steps and I was able to connect.

**Comment by nirui** [comment]
Can you connect other SSH servers successfully with Sshwifty?

The error `ssh: unexpected packet in response to channel open: <nil>` means Sshwifty received an invalid packet when trying to connect to the SSH server. It could mean a number of things, so it is not really easy to pin point the source of the problem.

If Sshwifty can connect to other SSH servers (say `tty.sdf.org`, you have to register an account first) but not your `localhost`, maybe take look `/var/log/auth.log` on the target SSH server (`cat /var/log/auth.log | grep "sshd"`), see if there is any `fatal` errors.
